version: "3.8"
networks:
  alsinet:
    external: true
services:
  web:
    build: .
    container_name: ecom
    image: ecom
    ports:
      - 1234:5050
    environment:
      - FLASK_RUN_PORT=$FLASK_RUN_PORT
      - FLASK_HOST=$FLASKHOST
      - FLASK_APP=$FLASK_APP
      - DB_URL=$DB_URL
      - CONFIG=$CONFIG
      - SECRET_KEY=$SECRET_KEY
    volumes:
      - .env:/usr/src/app/ecom/.env
    networks:
      - alsinet

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - ./mongo:/data/db
    networks:
      - alsinet

  mongo-express:
    image: mongo-express
    restart: always
    ports:
        - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - alsinet

